# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=32, verbose_name='标题')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
        ),
    ]
